6 acceptance testing
Andex/QnA pull request #3
Opened 2021-08-07 20:07 UTC by Andex

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2021-08-08 13:06 UTC, vkurennov requested changes

2021-08-08 13:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def new;  end
нам не нужен этот  экшн и вид, т.к. ответы и форма нового ответа должны быть на странице вопроса (по заданию)

2021-08-08 13:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
нужно рендерить страницу вопроса, т.к. new для ответа вообще не должно быть

2021-08-08 13:06 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'answers/answer', answers: @question.answers
достаточно написать просто `render @quertion.answers`,это будет то же самое, только короче

2021-08-08 13:06 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +      expect(page).to have_content 'Your answer successfully created.'
тут надо еще проверить, что ответ появился на странице

2021-08-08 13:06 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +      click_on 'Delete answer'
перед удалением хорошо бы проверить, что текст ответа есть на странице, чтобы исключить ложно-положительный тест

2021-08-08 13:06 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +      click_on 'Delete question'
тут тоже стоит проверить, что контент вопроса есть на странице

2021-08-08 21:20 UTC, Andex commented on app/views/questions/show.html.slim
> += render 'answers/answer', answers: @question.answers
Тогда вью _answers рендерится дважды

2021-08-09 11:11 UTC, vkurennov approved these changes

2021-08-09 11:11 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'answers/answer', answers: @question.answers
а вот это странно. попробуй еще раз, возможно, это из-за того, что ранее не было проверки на `persisted?`

2021-08-09 13:04 UTC, merged